@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package xyz.crystaline.teggunnekcihc.block.trashcompactor;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;